var words = [
    'Domain Controller',
    'Switch',
    'Netzwerk',
    'Access',
    'Routing',
    'Sicherheit',
    'HARTING',
    'Layer',
    'Lernaufgaben',
    'Physikalisch',
    'Rahden',
    'Server',
    'Switch',
    'Redundanz',
];